zeppelin:
    build: .
    environment:
        - ENDPOINT=${ENDPOINT}
        - KEY=key.pem
        - ZEPPELIN_LOG_DIR=/logs
        - ZEPPELIN_NOTEBOOK_DIR=/notebook
    volumes:
        - "./keys:/keys"
        - "./logs:/logs"
        - "./notebook:/notebook"
    ports:
        - "8080:8080"
